import dbConnect from "@/lib/mongoose";
import { JournalEntry, Account } from "@/models";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export const dynamic = 'force-dynamic';

export default async function AccountingPage() {
  await dbConnect();
  
  const entries = await JournalEntry.find()
    .populate('lines.accountId')
    .sort({ date: -1 })
    .limit(50)
    .lean();

  const accounts = await Account.find().sort({ code: 1 }).lean();

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">Accounting & General Ledger</h2>
        <p className="text-muted-foreground">
          Double-entry journal records automatically generated by the AI Accounting Engine.
        </p>
      </div>
      
      <div className="grid gap-6 md:grid-cols-3">
        <div className="md:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Recent Journal Entries</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-8">
                {entries.map((entry: any) => (
                  <div key={entry._id} className="border rounded-md p-0 overflow-hidden">
                    <div className="bg-zinc-50 border-b p-3 flex justify-between items-center text-sm">
                      <div className="font-medium text-zinc-900">
                        {entry.voucherNumber} <span className="text-muted-foreground ml-2">{new Date(entry.date).toLocaleDateString()}</span>
                      </div>
                      <div className="text-muted-foreground italic">
                        {entry.description}
                      </div>
                    </div>
                    <Table>
                      <TableHeader>
                        <TableRow className="hover:bg-transparent">
                          <TableHead>Account</TableHead>
                          <TableHead className="text-right">Debit</TableHead>
                          <TableHead className="text-right">Credit</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {entry.lines.map((line: any, idx: number) => (
                          <TableRow key={idx} className="hover:bg-transparent">
                            <TableCell className={`font-medium ${line.type === 'CREDIT' ? 'pl-8' : ''}`}>
                              {line.accountId?.code} - {line.accountId?.name}
                            </TableCell>
                            <TableCell className="text-right">
                              {line.type === 'DEBIT' ? `₹${line.amount.toLocaleString()}` : ''}
                            </TableCell>
                            <TableCell className="text-right">
                              {line.type === 'CREDIT' ? `₹${line.amount.toLocaleString()}` : ''}
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                ))}

                {entries.length === 0 && (
                  <p className="text-center text-muted-foreground py-8">No journal entries found. Approve transactions to auto-generate entries.</p>
                )}
              </div>
            </CardContent>
          </Card>
        </div>

        <div>
          <Card>
            <CardHeader>
              <CardTitle>Chart of Accounts Overview</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Account</TableHead>
                    <TableHead className="text-right">Balance</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {accounts.map((acc: any) => (
                    <TableRow key={acc._id}>
                      <TableCell>
                        <div className="font-medium">{acc.name}</div>
                        <div className="text-xs text-muted-foreground">{acc.code} • {acc.type}</div>
                      </TableCell>
                      <TableCell className="text-right font-semibold">
                        ₹{acc.balance.toLocaleString()}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
